apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: traefik

  listeners:
    - name: http
      protocol: HTTP
      # This port must mach the entrypoint configured in the helm chart values!
      port: 8000
      allowedRoutes:
        namespaces:
          from: All 

            #- name: https
            #  protocol: HTTPS
            #  port: 443
            #  tls:
            #    mode: Terminate
            #    certificateRefs:
            #      - name: secret-tls
            #        namespace: default

            #  allowedRoutes:
            #    namespaces:
            #      from: Same
