apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sample-routes
  namespace: kong
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: '/billing'
    backendRefs:
    - name: billing
      kind: Service
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: '/comments'
    backendRefs:
    - name: comments
      kind: Service
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: '/invoice'
    backendRefs:
    - name: invoice
      kind: Service
      port: 80