apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: default
spec:
  gatewayClassName: traefik

  listeners:
      # This name must mach the entrypoint configured in the helm chart values!
    - name: web
      protocol: HTTP
      # This port must mach the entrypoint configured in the helm chart values!
      port: 8000
      allowedRoutes:
        namespaces:
          from: All 
      # This name must mach the entrypoint configured in the helm chart values!
    - name: websecure
      protocol: HTTPS
      # This port must mach the entrypoint configured in the helm chart values!
      port: 8443
      tls:
        mode: Terminate
        certificateRefs:
          - name: my-tls-secret
            namespace: default
      allowedRoutes:
        namespaces:
          from: All 